services:
  app:
    image: eyalankri/oktopost-api:latest
    container_name: oktopost-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SA_PASSWORD=${SA_PASSWORD}
      - Redis=redis:6379
      - ConnectionStrings__DefaultConnection=Server=tcp:oktopos.database.windows.net,1433;Initial Catalog=OkToPost;Persist Security Info=False;User ID=eyalankri;Password=Eyal$1q2w!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - "8080:80"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  sqlserver-data:

networks:
  backend:
