
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: OkToPost/Dockerfile
    container_name: oktopost-api
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    networks:
      - backend

  tests:
    build:
      context: .
      dockerfile: OkToPost.Tests/Dockerfile
    container_name: oktopost-tests
    depends_on:
      - db
      - redis
    networks:
      - backend
volumes:
  sqlserver-data:

networks:
  backend: